# Generated by Django 4.2.30 on 2026-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=220)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('order', 'question'),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('other', 'Other')], default='residential', max_length=20)),
                ('details', models.TextField(verbose_name='Project details')),
                ('source', models.CharField(choices=[('landing', 'Landing page form'), ('signup', 'Sign-up page'), ('phone', 'Phone call'), ('referral', 'Referral')], default='landing', max_length=20)),
                ('is_contacted', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('renovation', 'Renovation & Remodeling'), ('infrastructure', 'Infrastructure')], default='residential', max_length=20)),
                ('description', models.TextField(help_text='Short summary shown in the gallery modal.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL when no upload exists.')),
                ('client', models.CharField(blank=True, max_length=140)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('order', '-completed_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(default='fa-solid fa-helmet-safety', help_text='Font Awesome class, e.g. fa-solid fa-building', max_length=80)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='BuildCorp', max_length=80)),
                ('tagline', models.CharField(default='Building the Future, Restoring the Past.', max_length=160)),
                ('hero_eyebrow', models.CharField(default='Licensed & insured · Design-build since 2005', max_length=120)),
                ('hero_headline', models.CharField(default='Building the Future, Restoring the Past.', max_length=200)),
                ('hero_subheadline', models.TextField(default='Your trusted partner for residential and commercial construction. From concept to completion, we deliver excellence with integrity.')),
                ('hero_spline_url', models.URLField(blank=True, help_text='Spline scene .splinecode URL.')),
                ('hero_video_url', models.URLField(blank=True, help_text='Optional looping MP4 fallback.')),
                ('hero_video_poster', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_primary_cta_label', models.CharField(default='Request a Consultation', max_length=60)),
                ('hero_secondary_cta_label', models.CharField(default='View Our Work', max_length=60)),
                ('about_heading', models.CharField(default='Who We Are', max_length=160)),
                ('about_body', models.TextField(default='Founded in 2005, BuildCorp has been at the forefront of innovative construction, delivering more than 480 residential and commercial projects across the region. Our in-house architects, engineers and site teams work as one unit, which means fewer hand-offs, tighter schedules and a single point of accountability for you.')),
                ('about_body_secondary', models.TextField(blank=True, default='We are licensed, bonded and fully insured, and we hold our crews to a safety standard that goes well beyond the minimum. Every project is led by a dedicated project manager who reports to you weekly with photos, budgets and next steps.')),
                ('about_image_primary', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_image_secondary', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_image_tertiary', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('years_experience', models.PositiveIntegerField(default=21)),
                ('projects_completed', models.PositiveIntegerField(default=480)),
                ('team_members', models.PositiveIntegerField(default=65)),
                ('on_time_rate', models.PositiveIntegerField(default=98, help_text='Percentage on time.')),
                ('contact_email', models.EmailField(default='hello@buildcorp.example', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (555) 010-2030', max_length=40)),
                ('contact_address', models.CharField(default='1200 Ironworks Avenue, Suite 400, Denver, CO 80216', max_length=200)),
                ('office_hours', models.CharField(default='Mon – Fri · 7:30am – 6:00pm', max_length=120)),
                ('footer_tagline', models.CharField(default='Design-build construction delivered with integrity, transparency and craftsmanship.', max_length=220)),
                ('footer_copyright', models.CharField(default='Duracast', max_length=120)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
            ],
            options={
                'verbose_name': 'site content',
                'verbose_name_plural': 'site content',
            },
        ),
    ]
